function preload() {
  imagen1 = loadImage('data/imagen1.jpg');
  imagen2 = loadImage('data/imagen2.jpg');
  imagen3 = loadImage('data/imagen3.jpg');
  imagen4 = loadImage('data/imagen4.jpg');
  imagen5 = loadImage('data/imagen5.jpg');
  imagen6 = loadImage('data/imagen6.jpg');
  imagen7 = loadImage('data/imagen7.jpg');
  imagen8 = loadImage('data/imagen8.jpg');
  imagen9 = loadImage('data/imagen9.jpg');
  imagen10 = loadImage('data/imagen10.jpg');
  imagen11 = loadImage('data/imagen11.jpg');
  imagen12 = loadImage('data/imagen12.jpg');
  imagen13 = loadImage('data/imagen13.jpg');
  imagen14 = loadImage('data/imagen14.jpg');
  imagen15 = loadImage('data/imagen15.jpg');
  imagen16 = loadImage('data/imagen16.jpg');
  imagen17 = loadImage('data/imagen17.jpg');
  imagen18 = loadImage('data/imagen18.jpg');
  texto1 = loadStrings('data/texto1.txt');
}
